version: "3"
services:
  app:
    image: crud-typescript
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:

      - .:/app

      - node_modules:/app/node_modules
    depends_on:
      - postgres
  postgres:
    container_name: postgres_crud_typescript
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crud_typescript_db
    ports:
      - '5432:5432'
    volumes:
      - postgres-db:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin_crud_typescript
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: '123456'
    ports:
      - '15432:80'
    depends_on:
      - postgres

volumes:
  node_modules:
  postgres-db:
